### ISSUE TITLE
context menu outside of canvas doesnt work

### ISSUE THREAD

**Issue by cjquines** [cjquines/qboard#137]
it should work in the toolbar, the background, and on modals

**Comment by pihart** [comment]
hmm, i wouldn't have wanted it to do that.

on the toolbar, users should use the toolbar; of course, the context menu is primarily a mini toolbar (since we haven't implemented anything context-based).

on the modal, there should be no need to use anything from the context menu? or at least i don't see the use case

**Comment by cjquines** [comment]
oh i meant the native context menu not the qboard context menu. i think native context menu should work everywhere that is not canvas
