### ISSUE TITLE
Desktop version

### ISSUE THREAD

**Issue by Yu-Dylan** [cjquines/qboard#74]
Desktop verison where I can keep old qboards and keep my keybindings. A systems similar to Onenote would be nice.

**Comment by cjquines** [comment]
? qboard automatically saves keybindings. if you want to keep old qboards you can save the source files

**Comment by Yu-Dylan** [comment]
What if I work offline? I suppose that's the heart of the issue.

**Comment by cjquines** [comment]
it works offline; just save the page? its entirely client-side

**Comment by Yu-Dylan** [comment]
How do I save the page? I can export to PDF, or ctrl+s to get a .json and .html file. When I try using the .html file, it doesn't work (images aren't loaded, drawing doesn't work).

**Comment by pihart** [comment]
The left sidebar has all the file operations. Namely, what you're looking for are save, which exports the json file you're talking about, and open, which opens it as if you were opening a file on a desktop application. Like exporting, both of these actions are bindable to the keyboard.

There's also the option of dragging and dropping your saved json file onto the canvas instead of using the open action. Instead of replacing your current board, this would append the pages from the json file into the current board, beginning at the current page.

@cjquines Can you please label this issue as documentation

**Comment by cjquines** [comment]
fixed by 7de3a540dc280d2f3d9fe27ae948e2d7f8fca661

**Comment by pihart** [comment]
Todo: document all ways to import files
