### ISSUE TITLE
Text + TeX

### ISSUE THREAD

**Issue by Yu-Dylan** [cjquines/qboard#76]
Add text boxes (w/ bold, italics, subscript, superscript, highlighting, etc. -- most I probably won't use, but it's a good thing to add regardless) and latex rendering.

Edit: this is very obviously an enhancement, not something super important (except to me, latex is life).

**Comment by pihart** [comment]
I was thinking of implementing TeX (LaTeX math mode) but won't work on that for a few weeks. @cjquines said that textboxes were hard to export to pdf, but since TeX renders as SVG I don't think that's an issue.

This is related to #75

**Comment by cjquines** [comment]
when i last looked into this rendering as svg was pretty complicated. i dont see a nice way to make this work without using mathjax, with sucks, or doing something sketchy with fabric, which is hard.

the decision to not have text was intentional from the beginning. i still think it shouldnt have a text tool.

**Comment by Yu-Dylan** [comment]
Is there a specific reason besides "doing it will be hard"? I can understand that, but I don't get the intent behind no text.

**Comment by cjquines** [comment]
qboard never was supposed to be a general drawing solution, and it isn't. it's meant for giving lectures and for quick sketches. it's not meant for taking notes, it's not meant for write-ups.

**Comment by pihart** [comment]
There is a lecture use case for text, namely to prewrite slide titles or section headers. That said, it's not very important.

**Comment by cjquines** [comment]
if you want text in your slides you should be using a slideshow

**Comment by pihart** [comment]
You can't draw on a slideshow (which is one of the reasons for #69)

**Comment by cjquines** [comment]
you… can… and if you cant your slideshow app sucks

**Comment by pihart** [comment]
I mean of course you can annotate but shapes, drawing templates, even copy/paste don't exist on most apps

**Comment by pihart** [comment]
Caution: if implementing TeX, don't allow arbitrary escaping out of math mode. Otherwise (unless we are very careful about sandboxing) we have an xss vulnerability when someone shares the board as json or if we implement collaboration/spectating

**Comment by cjquines** [comment]
closing as old

**Comment by pihart** [comment]
don't think this should be closed

**Comment by cjquines** [comment]
i mean i don't see what else could happen on this issue, and same thing with all the other things that were commented? if there's no reason to keep it open, and in this case, it's a wontfix, then there's no reason to keep it open. if discussion changes we can reopen again.

**Comment by cjquines** [comment]
reopening in the light of #140 , but again its unclear whether this should be a thing. as another argument against: a lot of the keyboard operation in qboard is built to be doable one-handed. if you're going to use two hands on your keyboard… why are you drawing at all i guess?

i know it will be useful. i'm just asdfkgasdf because svg support with fabric has been spotty for a while and im not sure whether itll get better

**Comment by pihart** [comment]
> honestly this would probably get more use than laser and i think laser is justified?

Yeah, that's a good argument for including it. I also think this a better feature to have than half-filled shapes, yet I still think those should be included.

A few specific use cases I've had involve writing in problem statements; it's can be hard to do this effectively by hand. It's also good for cases where formatting (including emphasis/obliques/italics, boldface, ...) or readability are particularly important.

> if you're going to use two hands on your keyboard… why are you drawing at all i guess?

In addition to distinguishing characters with specific formatting, this is far more efficient when you already have the text. For example if you're doing a recitation of a problem set (and possibly of existing solutions), just paste the source code of the written statement. This is will be even more efficient when #88 is added: just select text from any app and drop it in; qboard will render it appropriately.

I will also repeat the earlier argument that properly prewritten headings can be really nice in a lecture setting. For example, if you're showing 20 different proofs of the infinitude of primes, it's better for both the lecturer and the audience to have the author for each proof already written on the respective slides.

---

On a tangential note, since mathjax doesn't support text mode environments, it might help to create our own mini-markdown with just bold and emphasis since these are all that seem to be supported in text mode. Of course, we can also be smart and wrap stuff in `$\underline{\text{.....}}$`, so we can support a number of formatting features that would otherwise be cumbersome to use. Here's what I'm thinking:
- `**&&&**` bold
- `*&&&*`, `_&&&_` emphasis
- `__&&&__` underline: 
- `--&&&--`, `^^&&&^^` overline? not necessary imo
- `~~&&&~~` strikethrough (midline)
- recursive composition of any two distinct items of the above
  - this might not be possible for bold italics without a specific override on our part

There is a choice between
* just replacing any found occurences with the latex code, and
* *only* supporting those items (plus anything within `$&&&$`); i.e. our LaTeX prompt is now instead a custom markdown prompt.

Writing a parser for either should be relatively easy, but the former would *technically* have to be made aware of LaTeX, while the latter would just need to know of an escaped dollar sign (`\$` )

**Comment by cjquines** [comment]
> since mathjax doesn't support text mode environments, it might help to create our own mini-markdown with just bold and emphasis since these are all that seem to be supported in text mode

sounds reasonable to open a new issue for this, as im merging #140 xp

**Comment by cjquines** [comment]
And Another Thing: if there's an error in rendering the latex, there's just a black box, which is not very user friendly

**Comment by pihart** [comment]
> And Another Thing: if there's an error in rendering the latex, there's just a black box, which is not very user friendly

Yes, this is true. If mathjax doesn't have a builtin way around this then I have no real solution (except for testing whether the image is a black box, which might actually be doable). The reason is, in addition to writing a LaTeX validator, we'd also need to know which environments and commands exist since `\begin{proof}A.\end{proof}` induces the same type of box, and that would be a practically unsolvable problem.
